name: CI
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Verify
        run: ./mvnw -B -ntp verify

      - name: Upload JAR
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: target/*.jar
